version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - SOCKET_IO_PORT
      - PORT
      - DATABASE_URL
      - DTABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - JWT_SECRET
      - S3_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - GOOGLE_ID
      - GOOGLE_SECRET
      - USER
      - PASS
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - REMOTE_PRIVATE_KEY
      - EC2_HOST
      - EC2_USERNAME
    image: ${ECR_REGISTRY}/trello:late
  service2:
    build:
      context: .
      dockerfile: Dockerfile.socket
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
    image: ${ECR_REGISTRY}/trello:latest
